# Generated by Django 6.0.5 on 2026-05-16 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('status', models.CharField(choices=[('planning', 'Em planejamento'), ('active', 'Em andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['created_at'],
            },
        ),
    ]
