# Generated by Django 6.0.5 on 2026-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade máxima'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('waitlisted', 'Lista de espera'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20, verbose_name='status'),
        ),
    ]
