# Generated by Django 6.0.5 on 2026-05-16 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('category', models.CharField(choices=[('general', 'Geral'), ('meeting', 'Reunião'), ('maintenance', 'Manutenção'), ('sports', 'Esportes'), ('social', 'Social'), ('urgent', 'Urgente')], default='general', max_length=20, verbose_name='categoria')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'anúncio',
                'verbose_name_plural': 'anúncios',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
